CLUSTAL multiple sequence alignment by MUSCLE (3.8)


EP300             MAENVVEPGPPSAKRPKLSSPALSASASDGTDFGSLFDLEHDLPDELI-NSTELGLTNGG
Octodondegus      MAENLLD-GPPNPKRAKLSSPGF--SANDSTDFGSLFDLENDLPDELIPNGGELGLLNSG
Papioanubis       MAENLLD-GPPNPKRAKLSSPGF--SANDSTDFGSLFDLENDLPDELIPNGGELGLLNSG
FLJ57039          ------------------------------------------------------------
Panpaniscus       MAENLLD-GPPNPKRAKLSSPGF--SANDSTDFGSLFDLENDLPDELIPNGGELGLLNSG
                                                                              

EP300             DINQLQTSLGMVQDAASKHKQLSELLRSGSSPNLNMGVGG--------PGQVMASQAQQS
Octodondegus      N---------LVPDAASKHKQLSELLRGGTGSSINPGIGNVSASSPVQQGLGGQAQGQPN
Papioanubis       N---------LVPDAASKHKQLSELLRGGSGSSINPGIGNVSASSPVQQGLGGQAQGQPN
FLJ57039          ------------------------------------------------------------
Panpaniscus       N---------LVPDAASKHKQLSELLRGGSGSSINPGIGNVSASSPVQQGLGGQAQGQPN
                                                                              

EP300             SPGLGLINSMVKSPMTQAGLTSPNM---GMGTSGPNQGPTQS--------TGMMNSPVNQ
Octodondegus      TTNMASLGPLGKSPLNQGDSSAASLPKQAASTSGPTPPASQALNPQAQKQVGLVTSSPAT
Papioanubis       SANMASLGAMGKSPLSQGDSSAPSLPKQAASTSGPTPAASQALNPQAQKQVGLATSSPAT
FLJ57039          ------------------------------------------------------------
Panpaniscus       SANMASLSAMGKSPLSQGDSSAPSLPKQAASTSGPTPPASQALNPQAQKQVGLATSSPAT
                                                                              

EP300             PAMGMNTGMNAGMN---PGMLAAGNGQGIMPN------QVMNGSIG-AGRGR-QNMQYPN
Octodondegus      SQTGPGICMNANFNQTHPGLLNSNSGHSLMNQAQQGQAQVMNGSLGAAGRGRGTGMPYPA
Papioanubis       SQTGPGICMNANFNQTHPGLLNSNSGHSLMNQASQGQAQVMNGSLGAAGRGRGAGMPYPT
FLJ57039          ------------------------------------------------------------
Panpaniscus       SQTGPGICMNANFNQTHPGLLNSNSGHSLINQASQGQAQVMNGSLGAAGRGRGAGMPYPT
                                                                              

EP300             PGM-GSAGNLLTEPLQQGSPQMGGQTGLRGPQP---LKMGMMNNPNPYGSPYTQNPGQQI
Octodondegus      PAMQGATSSVLAETLTQVSPQMAGHAGLNTAQAGGMTKMGITGNTSPFGQPFSQTGGQQM
Papioanubis       PAMQGATSSVLAETLTQVSPQMTGHAGLNTAQAGGMAKMGITGNTSPFGQPFSQAGGQPM
FLJ57039          ------------------------------------------------------------
Panpaniscus       PAMQGASSSVLAETLTQVSPQMTGHAGLNTAQAGGMAKMGITGNTSPFGQPFSQAGGQPM
                                                                              

EP300             GASGLGLQIQTKTVLSNNLSPFAMDKKAVPGGGMPNMGQQPAPQVQQPGLVTPVAQGMGS
Octodondegus      GATGVNPQLSSKQNMVNSLPAFPTDIKNTSVTNVPNMSQMQTSVGIVP------TQAIAT
Papioanubis       GATGVNPQLASKQSMVNSLPTFPTDIKNTSVTNVPNMSQMQTSVGIVP------TQGIAT
FLJ57039          -----------------------------------------------------------T
Panpaniscus       GATGVNPQLASKQSMVNSLPTFPTDIKNTSVTNVPNMSQMQTSVGIVP------TQAIAT
                                                                             :

EP300             GAHTADPEKRKLIQQQLVLLLHAHKCQRREQANGEVRQCNLPHCRTMKNVLNHMTHCQSG
Octodondegus      GP-TADPEKRKLIQQQLVLLLHAHKCQRREQANGEVRACSLPHCRTMKNVLNHMTHCQAG
Papioanubis       GP-TADPEKRKLIQQQLVLLLHAHKCQRREQANGEVRACSLPHCRTMKNVLNHMTHCQAG
FLJ57039          GP-TADPEKRKLIQQQLVLLLHAHKCQRREQANGEVRACSLPHCRTMKNVLNHMTHCQAG
Panpaniscus       GP-TADPEKRKLIQQQLVLLLHAHKCQRREQANGEVRACSLPHCRTMKNVLNHMTHCQAG
                  *. ********************************** *.******************:*

EP300             KSCQVAHCASSRQIISHWKNCTRHDCPVCLPLKNAGDKRNQQPILTGAPVGLGNP-SSLG
Octodondegus      KACQVAHCASSRQIISHWKNCTRHDCPVCLPLKNASDKRNQQTILGSPASGIQNTIGSVG
Papioanubis       KACQVAHCASSRQIISHWKNCTRHDCPVCLPLKNASDKRNQQTILGSPASGIQNTIGSVG
FLJ57039          KACQVAHCASSRQIISHWKNCTRHDCPVCLPLKNASDKRNQQTILGSPASGIQNTIGSVG
Panpaniscus       KACQVAHCASSRQIISHWKNCTRHDCPVCLPLKNASDKRNQQTILGSPASGIQNTIGSVG
                  *:*********************************.******.** ... *: *. .*:*

EP300             VGQQSAPNLSTVSQIDPSSIERAYAALGLPYQVNQMPTQPQVQAKNQQNQQPGQSPQGMR
Octodondegus      SGQQNATSLSNPNPIDPSSMQRAYAALGLPY-MNQPQTQLQPQVPGQQPAQP-PAHQQMR
Papioanubis       TGQQNATSLSNPNPIDPSSMQRAYAALGLPY-MNQPQTQLQPQVPGQQPAQP-QTHQQMR
FLJ57039          TGQQNATSLSNPNPIDPSSMQRAYAALGLPY-MNQPQTQLQPQVPGQQPAQP-QTHQQMR
Panpaniscus       TGQQNATSLSNPNPIDPSSMQRAYAALGLPY-MNQPQTQLQPQVPGQQPAQP-QTHQQMR
                   ***.*..**. . *****::********** :**  ** * *. .**  **  : * **

EP300             PMSNMSASPMGVNGGVGVQT----PSLLSDSMLHSAINSQNPMMSE---NASVPSLGPMP
Octodondegus      TLNPLGNNPMNIPAG-GITADQQPPNLISESALSTSLGATNPLMNDGSTSGNIGSLSTIP
Papioanubis       TLNPLGNNPMNIPAG-GITTDQQPPNLISESALPTSLGATNPLMNDGSNSGNIGTLSTIP
FLJ57039          TLNPLGNNPMNIPAG-GITTDQQPPNLISESALPTSLGATNPLMNDGSNSGNIGTLSTIP
Panpaniscus       TLNPLGNNPMNIPAG-GITTDQQPPNLISESALPTSLGATNPLMNDGSNSGNIGTLSTIP
                  .:. :. .**.: .* *: :    *.*:*:* * :::.: **:*.:   ...: :*..:*

EP300             TAAQPSTTGIRKQWHEDITQDLRNHLVHKLVQAIFPTPDPAALKDRRMENLVAYARKVEG
Octodondegus      TAAPPSSTGVRKGWHEHVTQDLRSHLVHKLVQAIFPTPDPAALKDRRMENLVAYAKKVEG
Papioanubis       TAAPPSSTGVRKGWHEHVTQDLRSHLVHKLVQAIFPTPDPAALKDRRMENLVAYAKKVEG
FLJ57039          TAAPPSSTGVRKGWHEHVTQDLRSHLVHKLVQAIFPTPDPAALKDRRMENLVAYAKKVEG
Panpaniscus       TAAPPSSTGVRKGWHEHVTQDLRSHLVHKLVQAIFPTPDPAALKDRRMENLVAYAKKVEG
                  *** **:**:** *** :*****.*******************************.****

EP300             DMYESANNRAEYYHLLAEKIYKIQKELEEKRRTRLQKQNMLPNAAGMVPVSMNPGPNMGQ
Octodondegus      DMYESANSRDEYYHLLAEKIYKIQKELEEKRRSRLHKQGILGNQPTL-PAPGAQAPVIPP
Papioanubis       DMYESANSRDEYYHLLAEKIYKIQKELEEKRRSRLHKQGILGNQPAL-PAPGAQPPVIPQ
FLJ57039          DMYESANSRDEYYHLLAEKIYKIQKELEEKRRSRLHKQGILGNQPAL-PAPGAQPPVIPQ
Panpaniscus       DMYESANSRDEYYHLLAEKIYKIQKELEEKRRSRLHKQGILGNQPAL-PAPGAQPPVIPQ
                  *******.* **********************:**:**.:* * . : *..    * :  

EP300             PQPGMTSNGPLPDPSMIRGSVPNQMMPRITPQSGLNQF-----GQMSMAQPPIVPRQTPP
Octodondegus      AQSVRPPNGPLPLP-----------VNRMQVSQGMNSFNPMSLGNVQLPQAPMGPRAASP
Papioanubis       AQPVRPPNGPLSLP-----------VNRMQVSQGMNSFNPMSLGNVQLPQAPMGPRAASP
FLJ57039          AQPVRPPNGPLSLP-----------VNRMQVSQGMNSFNPMSLGNVQLPQAPMGPRAASP
Panpaniscus       AQPVRPPNGPLSLP-----------VNRMQVSQGMNSFNPMSLGNVQLPQAPMGPRAASP
                  .*.  ..****. *           : *:  ..*:*.*     *::.:.*.*: ** :.*

EP300             LQHHGQLAQPGALNPPMGYGP-RMQQPSN---------------QGQFLPQTQFPSQ--G
Octodondegus      MNHSVQMNSMASV-PGMAISPSRMPQPPNMMGTHTNNMMAQAPAQNQFLPQSQFPSSSGA
Papioanubis       MNHSVQMNSMGSV-PGMAISPSRMPQPPNMMGAHSNNMMAQAPAQSQFLPQNQFPPSSGA
FLJ57039          MNHSVQMNSMGSV-PGMAISPSRMPQPPNMMGAHTNNMMAQAPAQSQFLPQNQFPSSSGA
Panpaniscus       MNHSVQMNSMGSV-PGMAISPSRMPQPPNMMGAHTNNMMAQAPAQSQFLPQNQFPSSSGA
                  ::*  *: . .:: * *. .* ** **.*               *.*****.***..  .

EP300             MNVTNIPLAPSSGQAPVSQAQMSSSSCPVNSPIMPPGSQGSHIHCPQLPQPALHQNSPSP
Octodondegus      MNVNSVGIGQPTSQTGVSQGQVPGAALP--NPLNMLGPQASQLPCPPVTQTPLH---QTP
Papioanubis       M---SVGMGQPPAQTGVSQGQVPGAALP--NPLNMLGPQASQLPCPPVTQSPLH---PTP
FLJ57039          M---SVGMGQPPAQTGVSQGQVPGAALP--NPLNMLGPQASQLPCPPVTQSPLH---PTP
Panpaniscus       M---SVGMGQPPAQTGVSQGQVPGAALP--NPLNMLGPQASQLPCPPVTQSPLH---PTP
                  *   .: :. ...*: ***.*:..:: *  .*:   *.*.*:: ** :.*..**    :*

EP300             VPSRTPTPHHTPPSIGAQQPPATTIPAP-VPTPPAMPPGPQSQALHPPPRQTPTPPTTQL
Octodondegus      PPASTAAGM---PSLQHPTPPGMTPPQPAAPTQPSTPVSSSGQTPTPTPGSVPSATQTQS
Papioanubis       PPASTAAGM---PSLQHTTPPGMTPPQPAAATQPSTPVSSSGQTPTPTPGSVPSATQTQS
FLJ57039          PPASTAAGM---PSLQHTTPPGMTPPQPAAPTQPSTPVSSSGQTPTPTPGSVPSATQTQS
Panpaniscus       PPASTAAGM---PSLQHTTPPGMTPPQPAAPTQPSTPVSSSGQTPTPTPGSVPSATQTQS
                   *: *.:     **:    **. * * * ..* *: * ....*:  *.* ..*:.. ** 

EP300             PQQVQPSLPA--APSADQPQQQPRSQQSTAASVPTPTAPLLPPQPATPLSQPAVSIEGQV
Octodondegus      TPTVQAAAQV--TPQPQTPVQPPSVATPQSSQQQQPT-PVHVQPPGTPLSQAATSIDNRV
Papioanubis       TPTVQAAAQAQVTPQPQTPVQPPSVATPQSSQQQ-PT-PVHAQPPGTPLSQAAASIDNRV
FLJ57039          TPTVQAAAQAQVTPQPQTPVQPPSVATPQSSQQQ-PT-PVHAQPPGTPLSQAAASIDNRV
Panpaniscus       TPTVQAAAQAQVTPQPQTPVQPPSVATPQSSQQQ-PT-PVHAQPPGTPLSQAAASIDNRV
                  .  **.:  .  :*..: * * *    . ::.   ** *:    *.*****.*.**:..*

EP300             SNPPSTSSTEVNSQAIAEKQPSQEVKMEAKMEVDQPEPADTQPEDIS-------------
Octodondegus      PTPSSVASAETSSQQPGPDIPVLEMKAEVQTEDTEPDPGESKGESRSEMMEEDLQGSSQV
Papioanubis       PTPSSVASAETNSQQPGPDVPVLEMKAETQTEDTEPDPGESKGEPRSEMMEEDLQGASQV
FLJ57039          PTPSSVASAETNSQQPGPDVPVLEMKTETQAEDTEPDPGESKGEPRSEMMEEDLQGASQV
Panpaniscus       PTPSSVASAETNSQQPGPDVPVLEMKTETQAEDTEPDPGESKGEPRSEMMEEDLQGASQV
                  ..*.*.:*:*..**  . . *  *:* *.: *  :*:*.::: *  *             

EP300             --ESKVEDCKMESTETEERSTELKTEIKEEEDQPSTSATQSSPAPGQSKKKIFKPEELRQ
Octodondegus      KEETDTVEQKSEQMEMDEKKPEIKVEAKEEEESSANGTASQSTSPSQPRKKIFKPEELRQ
Papioanubis       KEETDTAEQKSEPMEVDEKKPEVKVEVKEEEESSTNGTASQSTSPSQPRKKIFKPEELRQ
FLJ57039          KEETDIAEQKSEPMEVDEKKPEVKVEVKEEEESSSNGTASQSTSPSQPRKKIFKPEELRQ
Panpaniscus       KEETDIAEQKSEPMEVDEKKPEVKVEVKEEEESSSNGTASQSTSPSQPRKKIFKPEELRQ
                    *:.  : * *  * :*...*:*.* ****:..:..::..*.:*.*..***********

EP300             ALMPTLEALYRQDPESLPFRQPVDPQLLGIPDYFDIVKSPMDLSTIKRKLDTGQYQEPWQ
Octodondegus      ALMPTLEALYRQDPESLPFRQPVDPQLLGIPDYFDIVKNPMDLSTIKRKLDTGQYQEPWQ
Papioanubis       ALMPTLEALYRQDPESLPFRQPVDPQLLGIPDYFDIVKNPMDLSTIKRKLDTGQYQEPWQ
FLJ57039          ALMPTLEALYRQDPESLPFRQPVDPQLLGIPDYFDIVKNPMDLSTIKRKLDTGQYQEPWQ
Panpaniscus       ALMPTLEALYRQDPESLPFRQPVDPQLLGIPDYFDIVKNPMDLSTIKRKLDTGQYQEPWQ
                  **************************************.*********************

EP300             YVDDIWLMFNNAWLYNRKTSRVYKYCSKLSEVFEQEIDPVMQSLGYCCGRKLEFSPQTLC
Octodondegus      YVDDVWLMFNNAWLYNRKTSRVYKFCSKLAEVFEQEIDPVMQSLGYCCGRKYEFSPQTLC
Papioanubis       YVDDVWLMFNNAWLYNRKTSRVYKFCSKLAEVFEQEIDPVMQSLGYCCGRKYEFSPQTLC
FLJ57039          YVDDVWLMFNNAWLYNRKTSRVYKFCSKLAEVFEQEIDPVMQSLGYCCGRKYEFSPQTLC
Panpaniscus       YVDDVWLMFNNAWLYNRKTSRVYKFCSKLAEVFEQEIDPVMQSLGYCCGRKYEFSPQTLC
                  ****:*******************:****:********************* ********

EP300             CYGKQLCTIPRDATYYSYQNRYHFCEKCFNEIQGESVSLGDDPSQPQTTINKEQFSKRKN
Octodondegus      CYGKQLCTIPRDAAYYSYQNRYHFCEKCFTEIQGENVTLGDDPSQPQTTISKDQFEKKKN
Papioanubis       CYGKQLCTIPRDAAYYSYQNRYHFCEKCFTEIQGENVTLGDDPSQPQTTISKDQFEKKKN
FLJ57039          CYGKQLCTIPRDAAYYSYQNRYHFCEKCFTEIQGENVTLGDDPSQPQTTISKDQFEKKKN
Panpaniscus       CYGKQLCTIPRDAAYYSYQNRYHFCEKCFTEIQGENVTLGDDPSQPQTTISKDQFEKKKN
                  *************:***************.*****.*:************.*:**.*.**

EP300             DTLDPELFVECTECGRKMHQICVLHHEIIWPAGFVCDGCLKKSARTRKENKFSAKRLPST
Octodondegus      DTLDPEPFVDCKECGRKMHQICVLHYDIIWPSGFVCDNCLKKTGRPRKENKFSAKRLQTT
Papioanubis       DTLDPEPFVDCKECGRKMHQICVLHYDIIWPSGFVCDNCLKKTGRPRKENKFSAKRLQTT
FLJ57039          DTLDPEPFVDCKECGRKMHQICVLHYDIIWPSGFVCDNCLKKTGRPRKENKFSAKRLQTT
Panpaniscus       DTLDPEPFVDCKECGRKMHQICVLHYDIIWPSGFVCDNCLKKTGRPRKENKFSAKRLQTT
                  ****** **:*.*************::****:*****.****:.*.*********** :*

EP300             RLGTFLENRVNDFLRRQNHPESGEVTVRVVHASDKTVEVKPGMKARFVDSGEMAESFPYR
Octodondegus      RLGNHLEDRVNKFLRRQNHPEAGEVFVRVVASSDKTVEVKPGMKSRFVDSGEMSESFPYR
Papioanubis       RLGNHLEDRVNKFLRRQNHPEAGEVFVRVVASSDKTVEVKPGMKSRFVDSGEMSESFPYR
FLJ57039          RLGNHLEDRVNKFLRRRNHPEAGEVFVRVVASSDKTVEVKPGMKSRFVDSGEMSESFPYR
Panpaniscus       RLGNHLEDRVNKFLRRQNHPEAGEVFVRVVASSDKTVEVKPGMKSRFVDSGEMSESFPYR
                  ***..**:***.****.****:*** **** :************:********:******

EP300             TKALFAFEEIDGVDLCFFGMHVQEYGSDCPPPNQRRVYISYLDSVHFFRPKCLRTAVYHE
Octodondegus      TKALFAFEEIDGVDVCFFGMHVQEYGSDCPPPNTRRVYISYLDSIHFFRPRCLRTAVYHE
Papioanubis       TKALFAFEEIDGVDVCFFGMHVQEYGSDCPPPNTRRVYISYLDSIHFFRPRCLRTAVYHE
FLJ57039          TKALFAFEEIDGVDVCFFGMHVQEYGSDCPPPNTRRVYISYLDSIHFFRPRCLRTAVYHE
Panpaniscus       TKALFAFEEIDGVDVCFFGMHVQEYGSDCPPPNTRRVYISYLDSIHFFRPRCLRTAVYHE
                  **************:****************** **********:*****.*********

EP300             ILIGYLEYVKKLGYTTGHIWACPPSEGDDYIFHCHPPDQKIPKPKRLQEWYKKMLDKAVS
Octodondegus      ILIGYLEYVKKLGYVTGHIWACPPSEGDDYIFHCHPPDQKIPKPKRLQEWYKKMLDKAFA
Papioanubis       ILIGYLEYVKKLGYVTGHIWACPPSEGDDYIFHCHPPDQKIPKPKRLQEWYKKMLDKAFA
FLJ57039          ILIGYLEYVKKLGYVTGHIWACPPSEGDDYIFHCHPPDQKIPKPKRLQEWYKKMLDKAFA
Panpaniscus       ILIGYLEYVKKLGYVTGHIWACPPSEGDDYIFHCHPPDQKIPKPKRLQEWYKKMLDKAFA
                  **************.*******************************************.:

EP300             ERIVHDYKDIFKQATEDRLTSAKELPYFEGDFWPNVLEESIKELEQEEEERKREENT-SN
Octodondegus      ERIIHDYKDIFKQATEDRLTSAKELPYFEGDFWPNVLEESIKELEQEEEERKKEESTAAS
Papioanubis       ERIIHDYKDIFKQATEDRLTSAKELPYFEGDFWPNVLEESIKELEQEEEERKKEESTAAS
FLJ57039          ERIIHDYKDIFKQATEDRLTSAKELPYFEGDFWPNVLEESIKELEQEEEERKKEESTAAS
Panpaniscus       ERIIHDYKDIFKQATEDRLTSAKELPYFEGDFWPNVLEESIKELEQEEEERKKEESTAAS
                  ***:************************************************.**.* :.

EP300             ESTDVTKGDSKNAKKKKK------------------------------------------
Octodondegus      ETPEGSQGDSKNAKKKNNKKTNKNKSSISRANKKKPSMPNVSNDLSQKLYATMEKHKEVF
Papioanubis       ETTEGSQGDSKNAKKKNNKKTNKNKSSISRANKKKPSMPNVSNDLSQKLYATMEKHKEVF
FLJ57039          ETTEGSQGDSKNA-----------------------------------------------
Panpaniscus       ETTEGSQGDSKNAKKKNNKKTNKNKSSISRANKKKPSMPNVSNDLSQKLYATMEKHKEVF
                  *:.: ::******                                               

EP300             ------------------------------------------------------------
Octodondegus      FVIHLHAGPVINTLPPIVDPDPLLSCDLMDGRDAFLTLARDKHWEFSSLRRSKWSTLCML
Papioanubis       FVIHLHAGPVINTLPPIVDPDPLLSCDLMDGRDAFLTLARDKHWEFSSLRRSKWSTLCML
FLJ57039          ------------------------------------------------------------
Panpaniscus       FVIHLHAGPVINTLPPIVDPDPLLSCDLMDGRDAFLTLARDKHWEFSSLRRSKWSTLCML
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      VELHTQGQDRFVYTCNECKHHVETRWHCTVCEDYDLCINCYNTKSHTHKMVKWGLGLDDE
Papioanubis       VELHTQGQDRFVYTCNECKHHVETRWHCTVCEDYDLCINCYNTKSHAHKMVKWGLGLDDE
FLJ57039          ------------------------------------------------------------
Panpaniscus       VELHTQGQDRFVYTCNECKHHVETRWHCTVCEDYDLCINCYNTKSHAHKMVKWGLGLDDE
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      GSSQGEPQSKSPQESRRLSIQRCIQSLVHACQCRNANCSLPSCQKMKRVVQHTKGCKRKT
Papioanubis       GSSQGEPQSKSPQESRRLSIQRCIQSLVHACQCRNANCSLPSCQKMKRVVQHTKGCKRKT
FLJ57039          ------------------------------------------------------------
Panpaniscus       GSSQGEPQSKSPQESRRLSIQRCIQSLVHACQCRNANCSLPSCQKMKRVVQHTKGCKRKT
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      NGGCPVCKQLIALCCYHAKHCQENKCPVPFCLNIKHKLRQQQIQHRLQQAQLMRRRMATM
Papioanubis       NGGCPVCKQLIALCCYHAKHCQENKCPVPFCLNIKHKLRQQQIQHRLQQAQLMRRRMATM
FLJ57039          ------------------------------------------------------------
Panpaniscus       NGGCPVCKQLIALCCYHAKHCQENKCPVPFCLNIKHKLRQQQIQHRLQQAQLMRRRMATM
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      NTRNVPQQSLPSPTSAPPGTPTQQPSTPQTPQPPSQPQPSPVSMSPAGFPSVTRTQPPMT
Papioanubis       NTRNVPQQSLPSPTSAPPGTPTQQPSTPQTPQPPAQPQPSPVSMSPAGFPSVARTQPPTT
FLJ57039          ------------------------------------------------------------
Panpaniscus       NTRNVPQQSLPSPTSAPPGTPTQQPSTPQTPQPPAQPQPSPVSMSPAGFPSVARTQPPTT
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      VSAGKPTNQVQAPPPPAQPPPAAVEAARQIEREAQQQQHLYRVNINNGMPPGRTSMGTPG
Papioanubis       VSTGKPTSQVPAPPPPAQPPPAAVEAARQIEREAQQQQHLYRVNINNGMPPGRTGMGTPG
FLJ57039          ------------------------------------------------------------
Panpaniscus       VSTGKPTSQVPAPPPPAQPPPAAVEAARQIEREAQQQQHLYRVNINNSMPPGRTGMGTPG
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      SQMAPVGLNVPRPSQVSGPVMPSMQPGQWQQAPIPQQQTMAGMPRPVMSMQAQAAVAGPR
Papioanubis       SQMAPVSLNVPRPNQVSGPVMPSMPPGQWQQAPLPQQQPMPGLPRPVISMQAQAAVAGPR
FLJ57039          ------------------------------------------------------------
Panpaniscus       SQMAPVSLNVPRPNQVSGPVMPSMPPGQWQQAPLPQQQPMPGLPRPVISMQAQAAVAGPR
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      MPNVQPPRSISPSALQDLLRTLKSPSSPQQQQQVLNILKSNPQLMAAFIKQRTAKYVANQ
Papioanubis       MPSVQPPRSISPSALQDLLRTLKSPSSPQQQQQVLNILKSNPQLMAAFIKQRTAKYVANQ
FLJ57039          ------------------------------------------------------------
Panpaniscus       MPSVQPPRSISPSALQDLLRTLKSPSSPQQQQQVLNILKSNPQLMAAFIKQRTAKYVANQ
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      PGMQPQPGMQSQPGMQSQPSMHQQPGLQNLNAMQAGVPRPSVPPQQQAMGGLNPQGQALN
Papioanubis       PGMQPQPGLQSQPGMQPQPGMHQQPSLQNLNAMQAGVPRPGVPPQQQAMGGLNPQGQALN
FLJ57039          ------------------------------------------------------------
Panpaniscus       PGMQPQPGLQSQPGMQPQPGMHQQPSLQNLNAMQAGVPRPGVPPQQQAMGGLNPQGQALN
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      IMNPGHNPNMASMNPQYREMLRRQLL----QQQQQQQQQQQQQQSSASMAGGMAGHNQFQ
Papioanubis       IMNPGHNPNMASMNPQYREMLRRQLLQQQQQQQQQQQQQQQQQQGSAGMAGGMAGHGQFQ
FLJ57039          ------------------------------------------------------------
Panpaniscus       IMNPGHNPNMASMNPQYREMLRRQLLQQQQQQQQQQQQQQQQQQGSAGMAGGMAGHGQFQ
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      QPQGPGGYAPAM-QQQRMQQHLPIQGSSMGQMAAQMGQLGQMGQPGLGADSTPNIQQALQ
Papioanubis       QPQGPGGYPPAMQQQQRMQQHLPLQGSSMGQMAAQMGQLGQMGQPGLGADSTPNIQQALQ
FLJ57039          ------------------------------------------------------------
Panpaniscus       QPQGPGGYPPAMQQQQRMQQHLPLQGSSMGQMAAQMGQLGQMGQPGLGADSTPNIQQALQ
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      QRILQQQQMKQQIGSPGQPNPMSPQQHMLSGQPQASHLPGQQMTTSLSNQVRSPAPVQSP
Papioanubis       QRILQQQQMKQQIGSPGQPNPMSPQQHMLSGQPQASHLPGQQIATSLSNQVRSPAPVQSP
FLJ57039          ------------------------------------------------------------
Panpaniscus       QRILQQQQMKQQIGSPGQPNPMSPQQHMLSGQPQASHLPGQQIATSLSNQVRSPAPVQSP
                                                                              

EP300             ------------------------------------------------------------
Octodondegus      RPQSQPPHSSPSPRIQPQPSPHHVSPQTGSPHPGLAVTMASSMDQGHLGNPEQSAMLPQL
Papioanubis       RPQSQPPHSSPSPRIQPQPSPHHVSPQTGSPHPGLAVTMASSIDQGHLGNPEQSAMLPQL
FLJ57039          ------------------------------------------------------------
Panpaniscus       RPQSQPPHSSPSPRIQPQPSPHHVSPQTGSPHPGLAVTMASSIDQGHLGNPEQSAMLPQL
                                                                              

EP300             ------------------------------
Octodondegus      NTPNRSALSSELSLVGDTTGDTLEKFVEGL
Papioanubis       NTPSRSALSSELSLVGDTTGDTLEKFVEGL
FLJ57039          ------------------------------
Panpaniscus       NTPSRSALSSELSLVGDTTGDTLEKFVEGL
                                                
